#!/bin/bash
for i in {0,1,2,3,4,5,6,7}; 
	do for j in {0,1,2,3,4,5,6,7,8,9,A,B,C,D,E,F}; 
		do echo "#W:$i$j$i$j$i$j$i$j$i$j........."  > /dev/ttyUSB0
#		do echo "#W:$i$j$i$j$i$j$i$j$i$j";
	done; 
	sleep 0.1
done

sleep 1
for i in {0,1,2,3,4,5,6,7,8,9,A,B,C,D,E,F}; 
	do for j in {0,1,2,3,4,5,6,7,8,9,A,B,C,D,E,F}; 
		do echo "#r:$i$j....................."  > /dev/ttyUSB0
#		do echo "#R:$i$j";
	done; 
	sleep 0.1
done



