#!/bin/bash
for i in {0,1,2,3,4,5,6,7}; 
#for i in {0,1,2,3,4,5,6,7,8,9,A,B,C,D,E,F}; 
	do for j in {0,1,2,3,4,5,6,7,8,9,A,B,C,D,E,F}; 
		do echo "#w:$i$j$i$j$i$j$i$j$i$j"  > /dev/ttyUSB0
		sleep 0.003
	done; 
	sleep 0.1
done
