#!/bin/bash
#echo "#W:0112345678";
echo "#W:1012345678......."  > /dev/ttyUSB0
echo "#r:10....................."  > /dev/ttyUSB0
echo "#r:8F....................."  > /dev/ttyUSB0
echo "#r:90....................."  > /dev/ttyUSB0
echo "#r:91....................."  > /dev/ttyUSB0
echo "#r:92....................."  > /dev/ttyUSB0
sleep 0.1
echo "#W:1087654321......."  > /dev/ttyUSB0
echo "#r:10....................."  > /dev/ttyUSB0
echo "#r:8F....................."  > /dev/ttyUSB0
echo "#r:90....................."  > /dev/ttyUSB0
echo "#r:91....................."  > /dev/ttyUSB0
echo "#r:92....................."  > /dev/ttyUSB0
