# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/QLink_2020/constraints_copy.xdc

# Block Designs: bd/spi_clk_gen/spi_clk_gen.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==spi_clk_gen || ORIG_REF_NAME==spi_clk_gen} -quiet] -quiet

# IP: bd/spi_clk_gen/ip/spi_clk_gen_clk_wiz_0_0/spi_clk_gen_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==spi_clk_gen_clk_wiz_0_0 || ORIG_REF_NAME==spi_clk_gen_clk_wiz_0_0} -quiet] -quiet

# XDC: bd/spi_clk_gen/spi_clk_gen_ooc.xdc
