set_property IOSTANDARD LVCMOS33 [get_ports {LEDS_O[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDS_O[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDS_O[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDS_O[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDS_O[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDS_O[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDS_O[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDS_O[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports STATUSLED_O]
#set_property PACKAGE_PIN P14 [get_ports {LEDS_O[0]}]
#set_property PACKAGE_PIN P15 [get_ports {LEDS_O[1]}]
#set_property PACKAGE_PIN R15 [get_ports {LEDS_O[2]}]
#set_property PACKAGE_PIN R10 [get_ports {LEDS_O[3]}]
#set_property PACKAGE_PIN R11 [get_ports {LEDS_O[4]}]
#set_property PACKAGE_PIN M9 [get_ports {LEDS_O[5]}]
#set_property PACKAGE_PIN P9 [get_ports {LEDS_O[6]}]
#set_property PACKAGE_PIN P8 [get_ports {LEDS_O[7]}]
#set_property PACKAGE_PIN L13 [get_ports RX_I]
#set_property PACKAGE_PIN K15 [get_ports TX_O]
set_property IOSTANDARD LVCMOS33 [get_ports CLK100_I]
set_property IOSTANDARD LVCMOS33 [get_ports RX_I]
set_property IOSTANDARD LVCMOS33 [get_ports TX_O]
set_property PACKAGE_PIN L5 [get_ports CLK100_I]

create_clock -period 10.000 [get_ports CLK100_I]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets CLK100_I_IBUF]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets SPI_SCLK_I_IBUF]

set_property PACKAGE_PIN A12 [get_ports RX_I]
set_property PACKAGE_PIN A5 [get_ports TX_O]
set_property PACKAGE_PIN M4 [get_ports {LEDS_O[0]}]
set_property PACKAGE_PIN M2 [get_ports {LEDS_O[1]}]
set_property PACKAGE_PIN E12 [get_ports {LEDS_O[2]}]
set_property PACKAGE_PIN C10 [get_ports {LEDS_O[3]}]
set_property PACKAGE_PIN J3 [get_ports {LEDS_O[4]}]
set_property PACKAGE_PIN E11 [get_ports {LEDS_O[5]}]
set_property PACKAGE_PIN F14 [get_ports {LEDS_O[6]}]
set_property PACKAGE_PIN F3 [get_ports {LEDS_O[7]}]
set_property PACKAGE_PIN D14 [get_ports STATUSLED_O]

set_property IOSTANDARD LVCMOS33 [get_ports SPI_MOSI_I]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_MOSI_O]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_SCLK_I]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_SCLK_O]
#set_property PACKAGE_PIN E12 [get_ports SPI_MOSI_I]
#set_property PACKAGE_PIN C10 [get_ports SPI_MOSI_O]
#set_property PACKAGE_PIN F14 [get_ports SPI_SCLK_I]
#set_property PACKAGE_PIN E11 [get_ports SPI_SCLK_O]
set_property PACKAGE_PIN K3 [get_ports SPI_MOSI_I]
set_property PACKAGE_PIN L2 [get_ports SPI_MOSI_O]
set_property PACKAGE_PIN F4 [get_ports SPI_SCLK_I]
set_property PACKAGE_PIN H3 [get_ports SPI_SCLK_O]


set_property SLEW FAST [get_ports SPI_MOSI_O]
set_property SLEW FAST [get_ports SPI_SCLK_O]
set_property DRIVE 16 [get_ports SPI_SCLK_O]
set_property DRIVE 16 [get_ports SPI_MOSI_O]
